cask_args appdir: '/Applications'

cask 'font-droid-sans-mono-for-powerline'

brew 'coreutils'
brew 'fvm'
brew 'gh'
brew 'go'
brew 'grc'
brew 'gnupg'
brew 'jq'
brew 'libgit2'
brew 'nvm'
brew 'openssl'
brew 'python3'
brew 'readline'
brew 'rg'
brew 'spaceman-diff'
brew 'thefuck'
brew 'wget'
brew 'zsh-completions'
