cask_args appdir: '/Applications'

brew 'ack'
brew 'coreutils'
brew 'go'
brew 'grc'
brew 'gnupg'
brew 'jp2a'
brew 'jq'
brew 'libgit2'
brew 'node'
brew 'openssl'
brew 'postgresql'
brew 'python3'
brew 'readline'
brew 'roundup'
brew 'spaceman-diff'
brew 'thefuck'
brew 'wget'
brew 'zsh-completions'
